class EnvironmentSettings:
    def __init__(self):
        self.workspace_dir = '/home/zyh/桌面/TBSI-main'    # Base directory for saving network checkpoints.
        self.tensorboard_dir = '/home/zyh/桌面/TBSI-main/tensorboard'    # Directory for tensorboard files.
        self.pretrained_networks = '/home/zyh/桌面/TBSI-main/pretrained_networks'
        self.lasot_dir = '/home/zyh/桌面/TBSI-main/data/lasot'
        self.got10k_dir = '/home/zyh/桌面/TBSI-main/data/got10k/train'
        self.got10k_val_dir = '/home/zyh/桌面/TBSI-main/data/got10k/val'
        self.lasot_lmdb_dir = '/home/zyh/桌面/TBSI-main/data/lasot_lmdb'
        self.got10k_lmdb_dir = '/home/zyh/桌面/TBSI-main/data/got10k_lmdb'
        self.trackingnet_dir = '/home/zyh/桌面/TBSI-main/data/trackingnet'
        self.trackingnet_lmdb_dir = '/home/zyh/桌面/TBSI-main/data/trackingnet_lmdb'
        self.coco_dir = '/home/zyh/桌面/TBSI-main/data/coco'
        self.coco_lmdb_dir = '/home/zyh/桌面/TBSI-main/data/coco_lmdb'
        self.lvis_dir = ''
        self.sbd_dir = ''
        self.imagenet_dir = '/home/zyh/桌面/TBSI-main/data/vid'
        self.imagenet_lmdb_dir = '/home/zyh/桌面/TBSI-main/data/vid_lmdb'
        self.lasher_train_dir = '/home/zyh/桌面/data/lasher/trainingset'
        self.lasher_test_dir = '/home/zyh/桌面/data/lasher/testingset'
        self.imagenetdet_dir = ''
        self.ecssd_dir = ''
        self.hkuis_dir = ''
        self.msra10k_dir = ''
        self.davis_dir = ''
        self.youtubevos_dir = ''
        self.vtuav_train_dir = '/home/zyh/桌面/data/VTUAV/train'
        self.vtuav_test_dir = '/home/zyh/桌面/data/VTUAV/test短'